SELECT DEGREE_TBL.degreeID, DEGREE_TBL.degreeName, DEGREE_TBL.degreeDuration FROM DEGREE_TBL 
INNER JOIN LECTURE_DEGREE_TBL ON (LECTURE_DEGREE_TBL.degreeID = DEGREE_TBL.degreeID) 
WHERE LECTURE_DEGREE_TBL.lectureID = 1;

SELECT * FROM LECTURE_TBL WHERE lectureEmail = 'james@gmail.com' AND lecturePassword = 'password!'

ALTER TABLE STUDENT_TBL 
DROP COLUMN studentPassword;

SELECT * FROM STUDENT_TBL;

SELECT * FROM COURSE_TBL;